print("por favor ingrese su nombre")
my_nombre = input()
print("por favor ingrese su apellido")
my_apellido = input()
print("por favor ingrese su edad")
my_edad = input()
print("por favor ingrese su direccion")
my_direccion = input()
print("por favor ingrese su telefono")
my_telefono = input()
print("por favor ingrese su genero")
my_genero = input()
print("los datos ingresados son:")
print("nombre:", my_nombre)
print("apellido:", my_apellido)
print("edad:", my_edad)
print("direccion:", my_direccion)
print("telefono:", my_telefono)
print("genero:", my_genero)